version: '2.2'
services:
  simple_flask_server:
    build: 
      context: .
      dockerfile: ./Dockerfile
      network: host
    image: simple_flask_server
    volumes:
      - ./volume/:/usr/src/app/volume/
    ports:
      - "5000:5000"
    cpu_count: 1
    cpus: 0.5
    mem_limit: 1g
    memswap_limit: 2g

